- src/assets/periodic-table.json
> docs(typo): modify the symbol of the bamboo tool

- browserslist
- tsconfig.json
differential builds https://angular.io/guide/deployment#differential-builds
> refactor: differential builds

- src/app/features/atom-details/atom-details.component.scss
fix:fixed question1 of issue#14
> fix:fixed question1 of issue#14 

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- package.json
Use local Angular CLI, so that CI does not need to install CLI globally.
> refactor: use local ng

- .github/workflows/ci.yml
- .github/workflows/pr.yml
[setup-node actions](https://github.com/actions/setup-node) have already installed yarn
> refactor: no need install yarn

- .stylelintrc.json
- package.json
- src/app/features/markdown-render/markdown-render.component.scss
- src/app/features/periodic-table/app-phase/app-phase.component.scss
- src/app/features/periodic-table/atom-details/atom-details.component.scss
- src/app/features/periodic-table/atom/atom.component.scss
- src/app/features/periodic-table/periodic-table/periodic-table.component.scss
- src/app/features/rating-radar-chart/markdown-rating/markdown-rating.component.scss
- src/app/presentation/case-study/case-study.component.scss
- src/app/presentation/design/path/path.component.scss
- src/app/presentation/home/home.component.scss
- src/app/presentation/ledge-helper/ledge-helper.component.scss
- src/app/presentation/solution/solution.component.scss
- yarn.lock
> fix: fix stylelint issue

- projects/ledge-render/src/lib/ledge-render.component.html
- projects/ledge-render/src/lib/ledge-render.component.scss
- src/app/presentation/home/home.component.scss
- fix stylelint issue 
- fix process-card column gap ccording to the UI
> fix: process-card column gap & stylelint error

- projects/ledge-render/src/lib/components/ledge-step-line/ledge-step-line.component.html
- projects/ledge-render/src/lib/components/ledge-step-line/ledge-step-line.component.scss
- projects/ledge-render/src/lib/components/ledge-step-line/ledge-step-line.component.ts
- projects/ledge-render/src/lib/ledge-render.component.html
- projects/ledge-render/src/lib/ledge-render.component.scss
- projects/ledge-render/src/lib/ledge-render.component.ts
- src/app/presentation/home/home.component.html
- src/app/presentation/home/home.component.scss
- src/app/presentation/home/home.component.ts
ledge-helper增加step-line示例，新增step-line组件
> modify homePage

- src/styles/_markdown.scss
> fix: make menu item in one line #82

- projects/ledge-render/src/lib/components/ledge-table-step/ledge-table-step.component.html
- projects/ledge-render/src/lib/components/ledge-table-step/ledge-table-step.component.scss
- projects/ledge-render/src/lib/components/ledge-table-step/ledge-table-step.component.ts
- src/app/app.component.spec.ts
- src/app/features/markdown-render/tocify.ts
- src/app/presentation/home/home.component.scss
- Support dynamic  caculate row width
- Support for configuring column counts—— `column`
- Support for configuring column height——`rowHeight`
```json
config: { "column" : 5  }
```
```json
config: { "column" : 5,  "rowHeight" : "350px" }
```
> feat(ledge-table-step): support dynamic row width & config column、rowHeight

- src/assets/periodic-table.json
update Grafana configuration to resources add repo and tutorial
> update Grafana config

- src/assets/periodic-table.json
fix: add something about Gitea,GitHub,Git,Jenkins,Travis CI and JUnit.
> fix: add something about Gitea,GitHub,Git,Jenkins,Travis CI and JUnit.

- projects/ledge-render/src/lib/components/ledge-table-step/ledge-table-step.component.html
- projects/ledge-render/src/lib/components/ledge-table-step/ledge-table-step.component.ts
- src/assets/docs/casestudies/ledge.md
- table-step 默认不再需要配置 column 列数，根据页面宽度可以自适应最大列数（默认最小列数为4）
- 修改 case-study:ledge 流程渲染组件为 table-step
> refactor(table-step): support dynamic column count

- src/assets/docs/help.md
> 更新代码忘记了 --rebase   ，commit log就这样了。。。
> docs(helper): additional description

- README.md
> docs: add syntax component description

- README.md
- projects/ledge-render/src/lib/components/ledge-mermaid/ledge-mermaid.component.html
- projects/ledge-render/src/lib/components/ledge-mermaid/ledge-mermaid.component.spec.ts
- projects/ledge-render/src/lib/components/ledge-mermaid/ledge-mermaid.component.ts
- projects/ledge-render/src/lib/ledge-render.component.html
- projects/ledge-render/src/lib/ledge-render.component.ts
- projects/ledge-render/src/lib/ledge-render.module.ts
- projects/ledge-render/src/lib/pipes/tohtml.pipe.spec.ts
- projects/ledge-render/src/lib/pipes/tohtml.pipe.ts
close #130
存在问题需要帮查看，本地功能跑正常，单元测试没通过，没找到原因。
```
HeadlessChrome 80.0.3987 (Mac OS X 10.15.4) LedgeMermaidComponent should create FAILED
TypeError: Cannot read property 'length' of undefined
at <Jasmine>
at Object.render (http://localhost:9878/Users/giscafer/Code/ledge/node_modules/mermaid/dist/mermaid.core.js:14319:1)
at LedgeMermaidComponent.ngOnInit (http://localhost:9878/_karma_webpack_/src/lib/components/ledge-mermaid/ledge-mermaid.component.ts:4:12)
```
> feat(component:ledge-mermaid): add support mermaid

- src/assets/periodic-table.json
> docs(periodic): add packageManage discription

- src/app/presentation/job/create-job-dialog/JobData.ts
- src/app/presentation/job/create-job-dialog/create-job-dialog.component.html
- src/app/presentation/job/create-job-dialog/create-job-dialog.component.scss
- src/app/presentation/job/create-job-dialog/create-job-dialog.component.ts
- src/app/presentation/job/job.component.html
- src/app/presentation/job/job.component.scss
- src/app/presentation/job/job.component.ts
- src/app/presentation/job/job.module.ts
- src/app/shared/custom-material.module.ts
todo:
需协助：
- 提供一个token，用来请求api自动评论issue，建议注册一个小号作为机器人
- `#140`的issue 招聘信息模板更新一下，加入**岗位名称**，比如 `岗位名称：DevOps 工程师`
> feat(jobpage): get job info from issue comments

- src/app/presentation/job/create-job-dialog/JobData.ts
- src/app/presentation/job/create-job-dialog/create-job-dialog.component.html
- src/app/presentation/job/create-job-dialog/create-job-dialog.component.scss
- src/app/presentation/job/create-job-dialog/create-job-dialog.component.ts
- src/app/presentation/job/job.component.html
- src/app/presentation/job/job.component.ts
- src/app/presentation/job/job.module.ts
- `src/app/presentation/job/create-job-dialog/JobData.ts`  下配置 Github token 即可使用此功能
> feat(job): create job with github api

- projects/ledge-render/src/lib/chart/ledge-pipeline/ledge-pipeline.component.spec.ts
- projects/ledge-render/src/lib/chart/ledge-pipeline/ledge-pipeline.component.ts
- projects/ledge-render/src/lib/components/model/ledge-markdown-converter.ts
- projects/ledge-render/src/lib/ledge-render.component.ts
> refactor(ledge-pipeline): update markdown syntax from json to list

- scully.ledge.config.js
- src/app/presentation/skill-tree/skill-tree.component.ts
- src/assets/docs/skilltrees/frontend-skilltree.md
> feat: add front-end skilltree

- Jenkinsfile
- README.md
> feat: use CODING DevOps to deploy in China

- README.md
Fix ledge renders link:
- syntax see in [ledge render]
> docs: fix ledge render link

- src/assets/docs/guide_en.md
See https://github.com/phodal/ledge/issues/234
> Add guide in english

- src/assets/docs/home_en.md
See https://github.com/phodal/ledge/issues/237
> add home in english

- src/assets/docs/resources_en.md
Translate resources.md to english
> add resources in english

- src/assets/docs/pattern.md
Add a case of using DingTalk to practice chatops with the article link.
> docs: add a chatops case

- src/assets/periodic-table.json
> docs: add kubesphere

- src/assets/periodic-table.json
Add security tool's homepage and solve some mistakes.
> Add security tool's homepage.
